package view;

import control.CtrManterAuthor;
import control.CtrManterPublisher;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Authors;
import model.Publishers;



public class FormManterPublisher extends javax.swing.JFrame {

    CtrManterPublisher ctrManterPublisher;
    CtrManterAuthor ctrManterAuthor;
    Authors authors;
    Publishers publishers;
    
    
    public FormManterPublisher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtPublisher_Id = new javax.swing.JTextField();
        jTxtPublisher_Name = new javax.swing.JTextField();
        jTxtUrl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCbxtPublisher = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTxtPublisher_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPublisher_NameActionPerformed(evt);
            }
        });

        jLabel1.setText("Id: ");

        jLabel2.setText("Publisher Nome: ");

        jLabel3.setText("Url: ");

        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnIncluirMouseClicked(evt);
            }
        });

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnExcluirMouseClicked(evt);
            }
        });
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAlterarMouseClicked(evt);
            }
        });

        jCbxtPublisher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCbxtPublisherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jCbxtPublisher);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAlterar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtUrl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addComponent(jTxtPublisher_Name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtPublisher_Id, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel1))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPublisher_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPublisher_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnAlterar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtPublisher_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPublisher_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPublisher_NameActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        publishers = (Publishers) jCbxtPublisher.getSelectedValue();
        if (ctrManterPublisher.excluirPublisher(publishers)) {
            JOptionPane.showMessageDialog(this, "Objeto excluido");
        } else {
            JOptionPane.showMessageDialog(this, "Objeto não excluido");
        }

    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ctrManterPublisher = new CtrManterPublisher();
        ctrManterAuthor = new CtrManterAuthor();
        authors = new Authors();
        publishers = new Publishers();
        
        DefaultListModel listModel = new DefaultListModel();
        List listPub = new ArrayList();
        
        listPub = ctrManterPublisher.carregarPublisher();
            if (listPub != null) {
                Iterator i = listPub.iterator();
                while (i.hasNext()) {
                    Publishers pubList = (Publishers) i.next();
                    listModel.addElement(pubList);
                }
            }
        jCbxtPublisher.setModel(listModel);
        DefaultComboBoxModel modelCombo = new DefaultComboBoxModel();
        List listAut = ctrManterAuthor.carregarAuthors();
            if (listAut != null) {
                Iterator j = listAut.iterator();
                while (j.hasNext()) {
                    Authors autList = (Authors) j.next();
                    modelCombo.addElement(autList);
                }
            }
    }//GEN-LAST:event_formWindowActivated

    private void jCbxtPublisherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCbxtPublisherMouseClicked
       publishers = (Publishers) jCbxtPublisher.getSelectedValue();

        if (publishers != null) {
            jTxtPublisher_Id.setText(publishers.getPublisher_Id().toString());
            jTxtPublisher_Name.setText(publishers.getPublisher_Name());
            jTxtUrl.setText(publishers.getUrl());
            int cont;
        } else {
            JOptionPane.showMessageDialog(null, "Objeto não Encontrado!");
        }
    }//GEN-LAST:event_jCbxtPublisherMouseClicked

    private void jBtnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnExcluirMouseClicked
        publishers = (Publishers) jCbxtPublisher.getSelectedValue();
        if (ctrManterPublisher.excluirPublisher(publishers)) {
            JOptionPane.showMessageDialog(this, "Objeto excluido");
        } else {
        JOptionPane.showMessageDialog(this, "Objeto não excluido");
        }
    }//GEN-LAST:event_jBtnExcluirMouseClicked

    private void jBtnIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnIncluirMouseClicked
        publishers = new Publishers();
        publishers.setPublisher_Id(Integer.parseInt(jTxtPublisher_Id.getText()));
        publishers.setPublisher_Name(jTxtPublisher_Name.getText());
        publishers.setUrl(jTxtUrl.getText());
        if (ctrManterPublisher.gravarPublisher(publishers) == 1) {
            JOptionPane.showMessageDialog(null, "Objeto persistido");
        } else {
            JOptionPane.showMessageDialog(null, "Objeto não persistido");
        }
    }//GEN-LAST:event_jBtnIncluirMouseClicked

    private void jBtnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAlterarMouseClicked
    publishers = (Publishers) jCbxtPublisher.getSelectedValue();
        if (publishers != null) {
            publishers.setPublisher_Id(Integer.parseInt(jTxtPublisher_Id.getText()));
            publishers.setPublisher_Name(jTxtPublisher_Name.getText());
            publishers.setUrl(jTxtUrl.getText());
            if (ctrManterPublisher.alterarPublisher(publishers)) {
                JOptionPane.showMessageDialog(null, "Objeto persistido");
            }   
            else {
                JOptionPane.showMessageDialog(null, "Objeto não persistido");
            }
        } 
        else {
            JOptionPane.showMessageDialog(null, "Objeto não localizado");
        }
    }//GEN-LAST:event_jBtnAlterarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormManterPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormManterPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormManterPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormManterPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormManterPublisher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JList jCbxtPublisher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtPublisher_Id;
    private javax.swing.JTextField jTxtPublisher_Name;
    private javax.swing.JTextField jTxtUrl;
    // End of variables declaration//GEN-END:variables
}
